### PR TITLE
Fix for push notification sound.

### PR DESCRIPTION
**Pull request by michaelwschultz**
R: @mattmo

### CODE REVIEW

**Comment by brentvatne** [comment]
:+1:

**Comment by brentvatne** [comment]
let's make sure that if `localNotification.soundName` is nil, we provide an empty string

**Comment by mfmendiola** [comment]
done

**Comment by mfmendiola** [comment]
@brentvatne Is this okay to land?

**Comment by mattmo** [comment]
LGTM

**Pull request merged**
